### Iniciar sesión de usuario
POST http://localhost:5000/api/usuarios/login
Content-Type: application/json

{
    "username": "FabianF",
    "password": "usuario1"
}

###


### Obtener todos los usuarios
GET http://localhost:5000/api/usuarios/
Content-Type: application/json

###


### Crear un nuevo usuario
POST http://localhost:5000/api/usuarios/
Content-Type: application/json

{
    "username": "FabianF",
    "password": "usuario1",
    "role": "admin",
    "localId": "6707e96e46c6e33cdd8a322d"
}

###


### Eliminar un usuario específico
DELETE http://localhost:5000/api/usuarios/67166a2446d48b775cb79555
Content-Type: application/json

###

###Obtener Todas las Categorias de un Local
GET http://localhost:5000/api/categorias/local/6707e96e46c6e33cdd8a322d
Content-Type: application/json

###Obtener La Informacion de Una Categoria
GET http://localhost:5000/api/categorias/6719145c221ee1345ff947cd
Content-Type: application/json

### Obtener todos los productos de una Categoria específica
GET http://localhost:5000/api/productos?categoriaId=67093d9549e3527282fa085a
Content-Type: application/json

###


### Crear un nuevo producto (ejemplo adicional si lo necesitas)
POST http://localhost:5000/api/productos/
Content-Type: application/json

{
    "nombre": "Pan",
    "precio": 1.50,
    "categoriaId": "6707e96e46c6e33cdd8a322d"
}

